# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
---
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  md-check:
    runs-on: ubuntu-latest

    env:
      FILES: hello-bridge/README.md custom-contracts-bridging/README.md bridge-offchain-worker/README.md

    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install --git https://github.com/Trantorian1/md-command-check#96c5c4001f1f9cf73092272457a3d1bc11e85ee9

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: list tests
        run: |
          nix develop --command md-command-check --list --debug $FILES

      - name: md-command-check
        env:
          USC_DOCS_INFURA_KEY: ${{ secrets.USC_DOCS_INFURA_KEY }}
          USC_DOCS_TESTING_PK: ${{ secrets.USC_DOCS_TESTING_PK }}
          USC_DOCS_TESTING_ADDRESS: ${{ secrets.USC_DOCS_TESTING_ADDRESS }}
        run: |
          nix develop --command md-command-check --debug $FILES
